title: Creators.TF
description: "ok"
#url: //CreatorsTF.github.io

#repository: CreatorsTF/CreatorsTF.github.io

permalink: pretty
production: true
safe: true

# the format ctf seem to use in posts
date-format: "%B %d, %Y %k:%M"

plugins:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag

# Build settings
markdown: kramdown
theme: minima

kramdown:
    input: GFM
    auto_ids: false

defaults:
    - scope:
          path: ""
      values:
          layout: page

collections:
    posts:
        output: true

exclude:
    - /reference
    - Gemfile
    - Gemfile.lock
    - README.md
